name: Validate recipes

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    uses: CarstVaartjes/vonk-forge/.github/workflows/validate-recipe-library.yml@3dbc942d6e01f96472d25fa2ba0c8f10935b40cf
    with:
      platform_ref: 3dbc942d6e01f96472d25fa2ba0c8f10935b40cf
